apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      volumeMounts:
      - name: nginx
        mountPath: /etc/nginx
      volumes:
      - name: nginx
        configMap:
          name: demo-config
          items:
            - key: nginx.conf
