apiVersion: v1
kind: Service
metadata:
  name: web-nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 8080
  selector:
    app: web
    tier: pg
