apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: default
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  2;
    daemon off;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
        multi_accept on;
    }

    http {
      server {
        listen 80;
        location = / {
          proxy_pass       http://web:8000;
          proxy_set_header Host      $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }
    }
  pg:
    host: web-pg
    port: 5432
    username: postgres
    password: 123456
    database: postgres
  demo:
    host: demo-app
    port: 3000
    RAILS_ENV: production
    log_path: /tmp/