apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: default
data:
  pg:
    host: web-pg
    port: 5432
    username: postgres
    password: 123456
    database: postgres
  demo:
    host: demo-app
    port: 3000
    RAILS_ENV: production
    log_path: /tmp/