apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: zouqilin/rails5_web:current
        ports:
        - containerPort: 80
