apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  sessionAffinity: ClientIP
  ports:
    - port: 80
      nodePort: 30500
      targetPort: 80
  selector:
    app: web
    tier: frontend
  type: NodePort
