apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc
  labels:
    app: web
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      type: gluster
  resources:
    requests:
      storage: 1Gi
